[workspace]
name = "soma-env-6.0"
channels = ["conda-forge", "pytorch", "nvidia", "https://brainvisa.info/neuro-forge", "file:///volatile/home/hb261775/cati-forge-ns"]
platforms = ["linux-64"]
version = "6.0"

[dependencies]
python = ">=3.10,>=3.9,==3.11"
typer = "*"
conda-build = "*"
pytorch = { version="*", channel="pytorch" }
torchvision = { version="*", channel="pytorch" }
pyyaml = "*"
dateutils = "*"
cmake = "*"
gcc = "<15"
git = "*"
git-lfs="*"
gitpython = "*"
gxx = "<15"
libglu = "*"
libglvnd-devel-cos7-x86_64 = "*"
libstdcxx-devel_linux-64 = "*"
make = "*"
mesa-libgl-devel-cos7-x86_64 = "*"
mesalib-devel-only = "*"
pip = "*"
pyaml = "*"
pytest = "*"
rattler-build = ">=0.13"
six = "*"
sphinx = "*"
toml = "*"
virtualgl = "*"
"sigcpp-2.0" = "*"
libblitz = "*"
boost-cpp = "*"
gfortran = "*"
dcmtk = "*"
numpy = "<2"
libminc = "*"
openjpeg = "*"
pywebp = "*"
objgraph = "*"
graphviz = "*"
doxygen = "*"
pkgconfig = "*"
nipype = "*"
xlrd = "*"
xlwt = "*"
openpyxl = "*"
lark-parser = ">0.7.0"
python-dateutil = "*"
requests = "*"
cryptography = "*"
scikit-learn = "*"
pcl = "*"
configobj = "*"
pyqtwebkit = "*"
scipy = "*"
traits = { version = "<7", build = "*" }
spm12 = "*"
reportlab = "*"
libsvm = "*"
qwt = "*"
matplotlib = "*"
qtconsole = "*"
ipycanvas = "*"
ipywidgets = "*"
ipyevents = "*"
notebook = "*"
pygltflib = "*"
nodejs = "*"
xvfb = "*"
mesalib_software = "*"
pyqt = "*"
pyqtwebengine = "*"
ipykernel = "<7"
pycryptodome = "*"
pandas = "*"
libgl = "*"
libopengl = "*"
pydicom = "*"
pre-commit = "*"
scikit-image = "*"
gdb = "*"
sphinxcontrib-mermaid = "*"
myst-parser = "*"
sphinx-rtd-theme = "*"
sphinx-gallery = "*"
nbsphinx = "*"
nbconvert-pandoc = "*"
soma-openslide = "*"
black = "*"
dracopy = "*"
python-build = "*"
twine = "*"
gltf-transform = "*"
pyzmq = "*"
paramiko = "*"
wkhtmltopdf = "*"
filelock = "*"
# CATI dependencies
cati_execlog = "*"

[dependencies.libjpeg-turbo]
channel = "conda-forge"
version = ">=3.0.0"

[activation]
scripts = ["activate.sh"]

[pypi-dependencies]
cloc = ">=0.2.5, <0.3"
